spring.application.name=odeeh-service

firebase.credentials-json=${FIREBASE_CONFIG}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

flyway.create-schemas=true