spring.application.name=odeeh-service

server.address=0.0.0.0
server.port=8080

firebase.credentials-json=src/main/resources/firebase-service-account.json

spring.datasource.url=jdbc:postgresql://localhost:5432/odeeh_db
spring.datasource.username=postgres
spring.datasource.password=postgres
flyway.create-schemas=true